Repository sps-cl/2D-vap-2324-vacha, pull requests merged in 2023-09, with the labels that each got.

#1 Update: překlad nadpisu - ukázka
  02_lesson/GIT_CHEATSHEET.MD
Labels: enhancement

#3 Updated: další překlad
  02_lesson/GIT_CHEATSHEET.MD
Labels: enhancement

#5 Další překlad
  02_lesson/GIT_CHEATSHEET.MD
Labels: documentation

#6 Updated: Překlad nadpisu
  02_lesson/GIT_CHEATSHEET.MD
Labels: enhancement

#7 Přeložen GIT_CHEATSHEET do GIT_TAHAK
  02_lesson/GIT_CHEATSHEET.MD
  02_lesson/GIT_TAHAK.md
Labels: documentation, enhancement
